name: Release new version
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile on-screen version
        uses: xu-cheng/latex-action@v2
        with:
          root_file: TerrariaWiringTutorial_onscreen.tex
          latexmk_use_xelatex: true
      - name: Compile printed version
        uses: xu-cheng/latex-action@v2
        with:
          root_file: TerrariaWiringTutorial_printed.tex
          latexmk_use_xelatex: true
      - name: Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            TerrariaWiringTutorial_onscreen.pdf
            TerrariaWiringTutorial_printed.pdf
